### ISSUE TITLE
Mifare classic backdoor

### ISSUE THREAD

**Issue by nicowitteman** [pkourany/MFRC522_RFID_Library#11]
Hi Paul,
Have your read https://blog.quarkslab.com/mifare-classic-static-encrypted-nonce-and-backdoors.html? 
It would be nice if someone would port the python code to c++ for Particle and add it to your library. Not my forte, I am afraid.

**Comment by pkourany** [comment]
@nicowitteman, I didn't write the library, I only ported it to the Particle platform.  If another library, written in C++ is made available for the Arduino or similar platforms, I could look into porting it.

**Comment by nicowitteman** [comment]
Ok let's wait and see.
