### ISSUE TITLE
Issue compiling this library

### ISSUE THREAD

**Issue by frvalle** [pkourany/MFRC522_RFID_Library#3]
Hi, I'm trying to use the library but get this issue:
<img width="1280" alt="screen shot 2017-03-01 at 4 31 38 pm" src="https://cloud.githubusercontent.com/assets/9711690/23484447/9e160bda-fe9c-11e6-8470-b8d0ad6bb169.png">

Thank you

**Comment by pkourany** [comment]
@frvalle, seems that even Arduino don't have their story straight on 16 vs 32 bit `word`.  The library (which I did not author) uses the 16bit version of `word`.  I'll need to replace all occurrences of `word` with the more specific `uint16_t` type which is platform independent.  Stay tuned.

**Comment by mathis89** [comment]
Hey,
same problem here. I would really appreciate if you could fix it :)

**Comment by frvalle** [comment]
Hi,

By far I am not expert on this subject, but had the urgency of make it work.

I went to MFRC522.h, then to the line 
typedef uint16_t	word; and changed the 16 to 32 and the library compiled and worked

Hope that works for you

**Comment by pkourany** [comment]
@frvalle, thanks for the test!  Oddly, `word` is only used in one place in the code!  I'll be posting a fix later today.

**Comment by mathis89** [comment]
Thank you both for the quick answer! :-)

**Comment by pkourany** [comment]
Just posted the updated library.  Thanks!
