### ISSUE TITLE
conflicting declaration 'typedef uint16_t word'

### ISSUE THREAD

**Issue by miljushm** [pkourany/MFRC522_RFID_Library#4]
Veryfing code using this library in Particle Build fails with this error:
```
MFRC522/MFRC522.h:82:18: error: conflicting declaration 'typedef uint16_t word'
 typedef uint16_t word

**Comment by pkourany** [comment]
@miljushm, I'll be posting a fix later today.

**Comment by miljushm** [comment]
OK, I've already fixed - it was an easy one ;) Thanks for keeping the eye on this one, good work!

**Comment by pkourany** [comment]
Just posted the updated library.
