### ISSUE TITLE
Fails to complie in Particle Web IDE

### ISSUE THREAD

**Issue by richardhawthorn** [pkourany/MFRC522_RFID_Library#7]
Hi there

When compiling this library in the Particle IDE it returns an error

"lib/MFRC522/MFRC522.cpp:1631:1: control reaches end of non-void function [-Werror=return-type]"

It looks like the function MIFARE_UnbrickUidSector is expected to return a value, but isn't doing so in some conditions. 

Returning true at the end of this function (around line 1631 of MFRC522.cpp) looks like it should fix the problem.

**Comment by pkourany** [comment]
Merged the change.  Thanks!
